# Generated by Django 2.0 on 2018-11-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='Role',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='User_Name',
            field=models.CharField(max_length=30),
        ),
    ]
